### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by vcellmike** [noahlb123/bngl-visualizer#9]
1. Make either dynamic or static page for each model that will be on Examples page. Provide a template so MB can populate Examples page.
2. Dark/light switch - one page, MB will get it to different pages.

**Comment by noahlb123** [comment]
I actually already implemented templating before. You can use it with template.html. The best solution I found was just pasting the entire BNGL file as a string in the "bngl" variable. This will mean we will have to create a separate html file for every bngl template we want, but since github pages is static only, I can't think of a way to make a true template, let me know if you have any suggestions. I also re-enabled dark mode, but ran into the same problem with the static nature of github pages: I can't think of a way to preserve dark mode preferences across page navigation.
